library(GEOquery); library(limma); library(GSVA)
out <- normalizePath("outputs",mustWork=TRUE); base <- normalizePath("inputs/geo_series_matrix",mustWork=TRUE)
# Non-overlapping with the five prespecified mechanism modules.
cell_sets <- list(alveolar_epithelial=c("SFTPA1","SFTPA2","SFTPC","NAPSA"), endothelial=c("PECAM1","VWF","KDR","ESAM"), fibroblast_proxy=c("PDGFRA","COL5A1","C7","FBLN1"), macrophage=c("TYROBP","AIF1","CSF1R","C1QC"), lymphocyte=c("CD3D","CD3E","TRBC2","LCK"), ciliated_proxy=c("RSPH1","RSPH4A","HYDIN","CCDC153"))
read_ann <- function(gpl) { f<-gzfile(file.path("inputs",paste0(gpl,".annot.gz")),"rt"); repeat{z<-readLines(f,n=1,warn=FALSE);if(!length(z))stop("no annotation");if(z=="!platform_table_begin")break}; lines<-readLines(f,warn=FALSE);close(f);h<-strsplit(lines[1],"\t",fixed=TRUE)[[1]];x<-read.delim(text=paste(lines[-1],collapse="\n"),header=FALSE,sep="\t",quote='"',fill=TRUE,check.names=FALSE,col.names=h,comment.char="");x[,c("ID","Gene symbol")] }
get_expr <- function(gse) { es<-getGEO(filename=file.path(base,paste0(gse,"_series_matrix.txt.gz")),GSEMatrix=TRUE,getGPL=FALSE);e<-exprs(es);pd<-pData(es);a<-read_ann(as.character(pd$platform_id[1]));s<-toupper(trimws(sub("///.*$","",as.character(a$`Gene symbol`[match(rownames(e),a$ID)]))));keep<-!is.na(s)&s!="";avereps(e[keep,,drop=FALSE],ID=s[keep]) }
all_scores<-list(); avail<-list(); i<-0
for(gse in c("GSE10667","GSE24206","GSE32537")){e<-get_expr(gse); gs<-cell_sets[vapply(cell_sets,function(x)sum(x %in% rownames(e))>=2,logical(1))]; param<-gsvaParam(e,gs,kcdf="Gaussian",minSize=2,verbose=FALSE); z<-gsva(param,verbose=FALSE); i<-i+1;all_scores[[i]]<-data.frame(sample_id=colnames(z),dataset=gse,t(z),check.names=FALSE);avail[[i]]<-data.frame(dataset=gse,cell_proxy=names(gs),n_genes=vapply(gs,function(x)sum(x%in%rownames(e)),integer(1)))}
score<-do.call(rbind,all_scores);names(score)[-(1:2)]<-paste0("gsva_",names(score)[-(1:2)]);write.csv(score,file.path(out,"gsva_cell_marker_scores.csv"),row.names=FALSE,fileEncoding="UTF-8");write.csv(do.call(rbind,avail),file.path(out,"gsva_cell_marker_gene_coverage.csv"),row.names=FALSE,fileEncoding="UTF-8")
sc<-read.csv(file.path(out,"mechanism_module_scores.csv"),check.names=FALSE);d<-merge(subset(sc,dataset=="GSE32537"),subset(score,dataset=="GSE32537"),by=c("sample_id","dataset"),sort=FALSE);d$case<-factor(ifelse(d$group=="IPF_UIP","IPF_UIP",ifelse(d$group=="control","control",NA)),levels=c("control","IPF_UIP"));mods<-c("epithelial_barrier","mucociliary_clearance","injury_inflammation","oxidative_stress","fibrosis_epithelial_response");covs<-grep("^gsva_",names(d),value=TRUE);ans<-lapply(mods,function(m){q<-d[!is.na(d$case),c(m,"case",covs)];q<-q[complete.cases(q),,drop=FALSE];fit<-lm(as.formula(paste(m,"~case+",paste(covs,collapse="+"))),q);s<-summary(fit)$coefficients;data.frame(outcome=m,n=nrow(q),beta=s["caseIPF_UIP",1],se=s["caseIPF_UIP",2],p=s["caseIPF_UIP",4],r2=summary(fit)$r.squared)});ans<-do.call(rbind,ans);ans$fdr<-p.adjust(ans$p,"BH");write.csv(ans,file.path(out,"gsva_cell_sensitivity_models.csv"),row.names=FALSE,fileEncoding="UTF-8");capture.output({cat("GSVA marker-set sensitivity analysis; scores are relative enrichment, not cell fractions.\n");print(ans)},file=file.path(out,"gsva_cell_sensitivity_report.txt"))
