project <- normalizePath(".")
con <- gzfile(file.path(project,"inputs","GSE136831_AllCells.GeneIDs.txt.gz"),"rt")
idx <- read.delim(con, check.names=FALSE, stringsAsFactors=FALSE, quote='"')
close(con)
genes <- readLines(file.path(project,"outputs","GERD_direct_annotated_candidate_genes.txt"), warn=FALSE)
idx$HGNC_EnsemblAlt_GeneID <- gsub('"','',idx$HGNC_EnsemblAlt_GeneID,fixed=TRUE)
idx$Ensembl_GeneID <- gsub('"','',idx$Ensembl_GeneID,fixed=TRUE)
out <- data.frame(gene_symbol=genes, ensembl_gene_id=idx$Ensembl_GeneID[match(genes,idx$HGNC_EnsemblAlt_GeneID)], matched=genes %in% idx$HGNC_EnsemblAlt_GeneID)
write.table(out,file.path(project,"outputs","GERD_candidate_genes_GSE136831_index_match.tsv"),sep="\t",row.names=FALSE,quote=FALSE)
cat("candidate_genes",length(genes),"matched",sum(out$matched),"unmatched",sum(!out$matched),"\n")
print(out[!out$matched,,drop=FALSE])
