lib <- file.path(normalizePath("."), ".r_libs")
.libPaths(c(lib, .libPaths()))
library(MendelianRandomization)
project <- normalizePath(".")
d <- read.delim(file.path(project, "outputs", "GERD_to_IPF_mr_harmonised_primary.tsv"), check.names = FALSE)
m <- mr_input(bx=as.numeric(d$bx), bxse=as.numeric(d$se_x), by=as.numeric(d$by), byse=as.numeric(d$se_y), snps=as.character(d$rsid))
ivw <- mr_ivw(m)
eg <- mr_egger(m)
med <- mr_median(m)
out <- data.frame(method=c("IVW","Egger","Weighted median"), beta=c(ivw@Estimate,eg@Estimate,med@Estimate), se=c(ivw@StdError,eg@StdError.Est,med@StdError), p=c(ivw@Pvalue,eg@Pvalue.Est,med@Pvalue))
write.table(out, file.path(project, "outputs", "GERD_to_IPF_mr_mendelianrandomization_crosscheck.tsv"), sep="\t", row.names=FALSE, quote=FALSE)
print(out)
