lib <- file.path(normalizePath("."), ".r_libs")
.libPaths(c(lib, .libPaths()))
library(MRPRESSO)
project <- normalizePath(".")
d <- read.delim(file.path(project, "outputs", "GERD_to_IPF_mr_harmonised_primary.tsv"), check.names = FALSE)
dat <- data.frame(BetaOutcome=as.numeric(d$by), BetaExposure=as.numeric(d$bx), SdOutcome=as.numeric(d$se_y), SdExposure=as.numeric(d$se_x))
set.seed(41041)
res <- mr_presso(BetaOutcome="BetaOutcome", BetaExposure="BetaExposure", SdOutcome="SdOutcome", SdExposure="SdExposure", OUTLIERtest=TRUE, DISTORTIONtest=TRUE, data=dat, NbDistribution=500, SignifThreshold=0.05)
sink(file.path(project, "outputs", "GERD_to_IPF_mrpresso_raw.txt")); print(res); sink()
writeLines(c("# GERD to IPF MR-PRESSO audit v1", "", "- Input: 78 eligible harmonised SNPs after exclusion of 2 ambiguous palindromic variants.", "- Package: MRPRESSO installed in the project-local R library.", "- Simulation: NbDistribution=500; seed=41041.", "- Raw output: `outputs/GERD_to_IPF_mrpresso_raw.txt`.", "- This output is a sensitivity analysis and does not override the prespecified IVW or weighted-median estimates."), file.path(project, "outputs", "GERD_to_IPF_mrpresso_audit_v1.md"))
