fit <- read.csv("outputs/adjusted_linear_models_GSE32537.csv")
p <- read.csv("outputs/cross_dataset_direction_summary.csv")
mods <- c("epithelial_barrier","mucociliary_clearance","injury_inflammation","oxidative_stress","fibrosis_epithelial_response")
short <- c(epithelial_barrier="Epithelial barrier", mucociliary_clearance="Mucociliary clearance", injury_inflammation="Injury/inflammation", oxidative_stress="Oxidative stress", fibrosis_epithelial_response="Fibrosis/epithelial response")
fit <- fit[fit$analysis == "IPF_UIP_vs_control_adjusted", ]; fit <- fit[match(mods, fit$outcome), ]; fit$lo <- fit$beta - 1.96 * fit$se; fit$hi <- fit$beta + 1.96 * fit$se
direction <- matrix(NA_real_, nrow=length(mods), ncol=3, dimnames=list(mods,c("GSE10667","GSE24206","GSE32537")))
for(i in seq_len(nrow(p))) for(q in strsplit(p$direction_pattern[i], ";")[[1]]) { z<-strsplit(q,":")[[1]]; direction[p$module[i],z[1]] <- ifelse(z[2]=="higher_in_case",1,-1) }
draw <- function() { par(mfrow=c(1,2),mar=c(5,9.6,2.5,3.2),oma=c(0,0,2,0),family="sans",xpd=FALSE); y<-rev(seq_along(mods)); xr<-range(c(fit$lo,fit$hi))+c(-.25,1.15); plot(fit$beta,y,type="n",yaxt="n",xlim=xr,ylim=c(.5,5.5),xlab="Adjusted difference in module score\n(IPF/UIP minus control)",ylab=""); abline(v=0,lty=2,col="grey50"); axis(2,at=y,labels=short[mods],las=1,cex.axis=.76); segments(fit$lo,y,fit$hi,y,lwd=2,col="#0072B2"); points(fit$beta,y,pch=19,col="#0072B2",cex=1.05); text(fit$hi+.12,y,labels=sprintf("FDR %.3g",fit$fdr_within_all_models),pos=4,cex=.64); plot(NA,xlim=c(.5,3.5),ylim=c(.5,5.5),axes=FALSE,xlab="",ylab=""); for(i in seq_along(mods)) for(j in 1:3) { val<-direction[mods[i],j]; rect(j-.5,5.5-i,j+.5,6-i,col=ifelse(val>0,"#009E73","#D55E00"),border="white"); text(j,5.5-i,ifelse(val>0,"+","-"),cex=1.35,font=2) }; axis(1,at=1:3,labels=colnames(direction),cex.axis=.78); axis(2,at=rev(seq_along(mods)),labels=short[mods],las=1,cex.axis=.76); legend("top",legend=c("Higher in case","Lower in case"),fill=c("#009E73","#D55E00"),bty="n",cex=.7,horiz=TRUE,inset=c(0,-.1),xpd=TRUE); mtext("Prespecified mechanism pilot in public IPF lung tissue",outer=TRUE,cex=1.05,font=2) }
pdf("outputs/figure1_mechanism_pilot.pdf",width=10,height=5.6,useDingbats=FALSE); draw(); dev.off(); png("outputs/figure1_mechanism_pilot.png",width=3000,height=1680,res=300); draw(); dev.off()
