library(GEOquery)
library(limma)
out <- normalizePath("outputs", mustWork=TRUE); base <- normalizePath("inputs/geo_series_matrix", mustWork=TRUE)
markers <- list(epithelial=c("EPCAM","KRT8","KRT18","KRT19"), fibroblast=c("COL1A1","COL1A2","COL3A1","DCN","LUM"), macrophage=c("CD68","LST1","CTSS","FCER1G"), ciliated=c("FOXJ1","PIFO","DNAH5"), club=c("SCGB1A1"), leukocyte=c("PTPRC"))
read_ann <- function(gpl) { f<-gzfile(file.path("inputs",paste0(gpl,".annot.gz")),"rt"); repeat { z<-readLines(f,n=1,warn=FALSE); if(!length(z)) stop("annotation table missing"); if(z=="!platform_table_begin") break }; lines<-readLines(f,warn=FALSE); close(f); h<-strsplit(lines[1],"\t",fixed=TRUE)[[1]]; x<-read.delim(text=paste(lines[-1],collapse="\n"),header=FALSE,sep="\t",quote='"',fill=TRUE,check.names=FALSE,col.names=h,comment.char=""); x[,c("ID","Gene symbol")] }
score_gse <- function(gse) { es<-getGEO(filename=file.path(base,paste0(gse,"_series_matrix.txt.gz")),GSEMatrix=TRUE,getGPL=FALSE); e<-exprs(es); pd<-pData(es); ann<-read_ann(as.character(pd$platform_id[1])); a<-ann[match(rownames(e),ann$ID),]; sym<-toupper(trimws(sub("///.*$","",as.character(a$`Gene symbol`)))); keep<-!is.na(sym)&sym!=""; e<-avereps(e[keep,,drop=FALSE],ID=sym[keep]); s<-data.frame(sample_id=colnames(e),dataset=gse,stringsAsFactors=FALSE); for(nm in names(markers)){ g<-intersect(markers[[nm]],rownames(e)); s[[paste0("cell_",nm)]]<-if(length(g)) colMeans(t(scale(t(e[g,,drop=FALSE]))),na.rm=TRUE) else NA_real_ }; s }
cell <- do.call(rbind,lapply(c("GSE10667","GSE24206","GSE32537"),score_gse)); write.csv(cell,file.path(out,"cell_marker_proxy_scores.csv"),row.names=FALSE,fileEncoding="UTF-8")
sc<-read.csv(file.path(out,"mechanism_module_scores.csv"),check.names=FALSE); d<-merge(subset(sc,dataset=="GSE32537"),subset(cell,dataset=="GSE32537"),by=c("sample_id","dataset"),sort=FALSE); d$case<-factor(ifelse(d$group=="IPF_UIP","IPF_UIP",ifelse(d$group=="control","control",NA)),levels=c("control","IPF_UIP")); mods<-c("epithelial_barrier","mucociliary_clearance","injury_inflammation","oxidative_stress","fibrosis_epithelial_response"); cp<-paste0("cell_",names(markers)); fit_rows<-list(); k<-0
for(m in mods){ z<-d[!is.na(d$case),c(m,"case",cp)]; z<-z[complete.cases(z),,drop=FALSE]; if(nrow(z)<30) next; fit<-lm(as.formula(paste(m,"~ case +",paste(cp,collapse=" + "))),z); sm<-summary(fit)$coefficients; k<-k+1; fit_rows[[k]]<-data.frame(outcome=m,n=nrow(z),beta=sm["caseIPF_UIP",1],se=sm["caseIPF_UIP",2],p=sm["caseIPF_UIP",4],r2=summary(fit)$r.squared,stringsAsFactors=FALSE) }
fitout<-do.call(rbind,fit_rows); fitout$fdr<-p.adjust(fitout$p,"BH"); write.csv(fitout,file.path(out,"cell_proxy_adjusted_module_models.csv"),row.names=FALSE,fileEncoding="UTF-8")
capture.output({cat("Cell-marker proxy sensitivity analysis; proxies are not measured cell fractions.\n"); print(fitout)},file=file.path(out,"cell_proxy_sensitivity_report.txt"))
