library(GEOquery); library(limma); library(GSVA)
base <- normalizePath("inputs/geo_series_matrix",mustWork=TRUE); out <- normalizePath("outputs",mustWork=TRUE)
module <- c("TGFB1","COL1A1","COL3A1","SERPINE1","VIM","MMP7","KRT19")
read_ann <- function(gpl) { f<-gzfile(file.path("inputs",paste0(gpl,".annot.gz")),"rt");repeat{z<-readLines(f,n=1,warn=FALSE);if(!length(z))stop("missing annotation");if(z=="!platform_table_begin")break};l<-readLines(f,warn=FALSE);close(f);h<-strsplit(l[1],"\t",fixed=TRUE)[[1]];x<-read.delim(text=paste(l[-1],collapse="\n"),header=FALSE,sep="\t",quote='"',fill=TRUE,check.names=FALSE,col.names=h,comment.char="");x[,c("ID","Gene symbol")]}
locked <- read.csv(file.path(out,"mechanism_module_scores.csv"),check.names=FALSE)
prepare <- function(gse) { es<-getGEO(filename=file.path(base,paste0(gse,"_series_matrix.txt.gz")),GSEMatrix=TRUE,getGPL=FALSE);e<-exprs(es);pd<-pData(es);a<-read_ann(as.character(pd$platform_id[1]));s<-toupper(trimws(sub("///.*$","",as.character(a$`Gene symbol`[match(rownames(e),a$ID)]))));k<-!is.na(s)&s!="";e<-avereps(e[k,,drop=FALSE],ID=s[k]); lab<-locked$group[match(colnames(e),locked$sample_id)]; target<-if(gse=="GSE10667") "UIP" else if(gse=="GSE24206") "early_IPF" else "IPF_UIP"; group<-ifelse(lab==target,"case",ifelse(lab=="control","control",NA));list(expr=e,group=group)}
rows<-list();ii<-0
for(gse in c("GSE10667","GSE24206","GSE32537")){z<-prepare(gse);genes<-intersect(module,rownames(z$expr)); variants<-c("full",paste0("drop_",genes));for(v in variants){use<-if(v=="full")genes else setdiff(genes,sub("^drop_","",v));score<-colMeans(t(scale(t(z$expr[use,,drop=FALSE]))),na.rm=TRUE);a<-score[z$group=="case"];b<-score[z$group=="control"];a<-a[is.finite(a)];b<-b[is.finite(b)]; w<-wilcox.test(a,b,exact=FALSE);ii<-ii+1;rows[[ii]]<-data.frame(dataset=gse,method="mean_z",variant=v,n_genes=length(use),n_case=length(a),n_control=length(b),median_case=median(a),median_control=median(b),delta=median(a)-median(b),p=w$p.value,stringsAsFactors=FALSE)}; param<-gsvaParam(z$expr,list(fibrosis_epithelial_response=genes),kcdf="Gaussian",minSize=2,verbose=FALSE);g<-as.numeric(gsva(param,verbose=FALSE)[1,]);a<-g[z$group=="case"];b<-g[z$group=="control"];a<-a[is.finite(a)];b<-b[is.finite(b)];w<-wilcox.test(a,b,exact=FALSE);ii<-ii+1;rows[[ii]]<-data.frame(dataset=gse,method="GSVA",variant="full",n_genes=length(genes),n_case=length(a),n_control=length(b),median_case=median(a),median_control=median(b),delta=median(a)-median(b),p=w$p.value)}
r<-do.call(rbind,rows);r$fdr_within_dataset<-ave(r$p,r$dataset,FUN=function(x)p.adjust(x,"BH"));write.csv(r,file.path(out,"main_module_leave_one_out_and_gsva.csv"),row.names=FALSE,fileEncoding="UTF-8")
sumr<-do.call(rbind,lapply(split(r,r$variant),function(d)data.frame(variant=d$variant[1],methods=paste(unique(d$method),collapse=";"),datasets=nrow(d),positive_direction=sum(d$delta>0,na.rm=TRUE),negative_direction=sum(d$delta<0,na.rm=TRUE),max_p=max(d$p,na.rm=TRUE),stringsAsFactors=FALSE)));write.csv(sumr,file.path(out,"main_module_robustness_summary.csv"),row.names=FALSE,fileEncoding="UTF-8");capture.output({cat("Main-module robustness: leave-one-gene-out and GSVA.\n");print(r);cat("\nSummary\n");print(sumr)},file=file.path(out,"main_module_robustness_report.txt"))
